name: Django linter

on: [push]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8 --config .flake8 .
